### ISSUE TITLE
allow userScripts add in setting panel

### ISSUE THREAD

**Issue by lifesign** [cdloh/obsidian-cron#5]
As of now, it is only possible to add Obsidian commands in the settings panel. will userscripts also could be added in settings panel?

I really like the idea behind the Cron plugin, and I have been searching for a way to automate the creation of my daily, weekly, and yearly notes using the Templater and Periodic Notes plugins. Currently I still need to manually trigger the process, the Cron plugin provides a great way to automate this creative process.

**Comment by lifesign** [comment]
any idea ?

**Comment by cdloh** [comment]
hey @lifesign sorry for taking a hot minute to get back to you here.

I've thought about it and I don't plan on adding UserScripts to this plugin. The overhead seems not worth it when so many others do a better job of it.

There are ample plugins that support loading userscripts (QuickAdd etc). 

The plugin exposes and API - https://github.com/cdloh/obsidian-cron#api--userscripts

Please use that within userscripts via other plugins to add cronjobs.

Thanks.
