### ISSUE TITLE
[FR] Handling missed executions

### ISSUE THREAD

**Issue by jornamon** [cdloh/obsidian-cron#7]
Hi!

Thanks for the plugin! Nice idea.

I was trying to use it in combination with `Quickadd` plugin to add monthly tasks to my Kanban board. My tasks are just cards in the `Kanban` plugin.

As far as I can see, there is no handling of missed executions, so it the computer is off or Obsidian closed at the time the cron job is triggered, it will fail to add the monthly tasks, not good.....

Is there any way to achieve this (handling missed executions to make sure something is really done at least at the first available opportunity) or do you have it in your future plans?

**Comment by cdloh** [comment]
Hey @jornamon 👋 

This should be already happening! If it isn't there is a bug here that I've got to fix.

The cron isn't strictly a cron but just a timer that runs every X interval. Each job is evaluated each time and the last time it was meant to run is calculated. If the last time it was meant to run is AFTER the last successful run then the module will execute the job.

If you find it isn't happening some reproduction steps would be most appreciated.

**Comment by jornamon** [comment]
Thanks @cdloh! Yesterday I was testing the plugin but not this specifically and I got the impression it was ignoring missing executions. Let me test it properly and come back with a way to reproduce or confirming that is working. 

Just to be sure of the expected behavior, if the cron is executed (which happens every `Cron Interval` minutes if Obsidian is running, right?) and finds a job which should have been executed since the last cron execution, it does it immediately, is this correct? What would happen if a job should have been executed several times, is it run once or all the missing executions get run?

**Comment by cdloh** [comment]
> Just to be sure of the expected behavior, if the cron is executed (which happens every Cron Interval minutes if Obsidian is running, right?) and finds a job which should have been executed since the last cron execution, it does it immediately, is this correct?

That's correct.

> What would happen if a job should have been executed several times, is it run once or all the missing executions get run?

It'll only run once. It'll then update the last update time and things will continue normally from then on.

I thought about making it run for every instance it was meant to run between the last run and the current time but decided against it to keep it simple.

**Comment by jornamon** [comment]
> I thought about making it run for every instance it was meant to run between the last run and the current time but decided against it to keep it simple.

I think this is a good design decision, I just wanted to make sure I will test against the intended behavior. Maybe if the the plugin keeps growing, you could let the jobs to be configured for how to handle missed executions (skip, run once, run all), but I agree that run once is the best "default" behavior.

**Comment by jornamon** [comment]
Yeah, it definitely works as expected. The first day I was testing with jobs scheduled every minute and somehow I got the wrong impression.

Thanks again for the plugin and for your time. I don't think people realize yet how powerful this plugin can be, specially combined with QuickAdd 🚀

**Comment by cdloh** [comment]
Thanks for the kind words @jornamon !

Glad to hear it's all working as expected. Let me know if you hit any bugs in the future!
