### ISSUE TITLE
Daily note commands don't seem to work

### ISSUE THREAD

**Issue by RomanQrr** [cdloh/obsidian-cron#8]
I've been trying to make my daily notes pop up at specified time, but run into the problem that the command doesn't seem to do anything in the plugin. The interval is set to 1 minute. The job has a name, is scheduled for "* * * * *" or for "[minutes] [hour] * * *" where anything in [] is replaced with appropriate numbers. The commands tried are "daily-notes", "daily-notes:goto-next", "daily-notes:goto-prev", and "workspace:open-in-new-window". The last one works every time, others don't. The job is set to run. It is a fresh install of Obsidian.

**Comment by RomanQrr** [comment]
Nevermind, for some reason a lock got put onto the job without me clicking on it. Probably because job was tasked to run while I was modifying it.

**Comment by cdloh** [comment]
@RomanQrr if you can figure out a good way to reproduce this I'd love to put some safe guards in place :)
