### ISSUE TITLE
Run a cron command on a specific file?

### ISSUE THREAD

**Issue by zeltak** [cdloh/obsidian-cron#9]
Hi and thank you for this amazing plugin!

i actually discovered this via this conversation:

https://github.com/ivan-lednev/obsidian-task-archiver/issues/82#issuecomment-2118099295

and im wondering if i can request an option to run the cron command on a specific file?

thx alot!

Z

**Comment by cdloh** [comment]
Hi @zeltak 👋 

At present this wouldn't be possible no.

There are a few problems I for see with this.

To activate the command on a specific file it has to be active with the current editor. This would result in a potentially pretty shitty experience for the user as periodically their Obsidian would just swap files randomly, regardless of if they were presently doing this.

There might potentially be ways around this but will have to investigate. I wouldn't have super high hopes.

Thanks!

**Comment by zeltak** [comment]
thx for the update @cdloh !

**Comment by cdloh** [comment]
@zeltak I've had a look at this and it isn't really possible. I have no way of controlling other commands etc.

If you need to run it against a specific file like in your example I would need to make the editor change the current file which would create a really bad user experience as periodically your editor would effectively be out of your control.

You would need to get the plugin to expose an API so you could do it periodically against specific files.
